project_id = "dgeadmmbkvcsgizsnbpi"

[functions.api-keys]
verify_jwt = false

[functions.api-chat]
verify_jwt = false

[functions.api-users]
verify_jwt = false

[functions.api-calls]
verify_jwt = false

[functions.api-crypto]
verify_jwt = false

[functions.check-username]
verify_jwt = false

[functions.check-email]
verify_jwt = false
